Repository colorstackorg/oyster, pull requests merged in 2024-12, with the labels that each got.

#624 chore: my first contribution 🚀
  CONTRIBUTORS.yml
Labels: Ready for Rami :white_check_mark:

#651 chore: my first contribution 🚀
  CONTRIBUTORS.yml
Labels: Ready :white_check_mark:

#563 feat: store member directory profile urls on slack profile 👥
  packages/core/src/infrastructure/bull/bull.types.ts
  packages/core/src/modules/slack/events/slack-workspace-joined.ts
  packages/core/src/modules/slack/slack-profile.ts
Labels: Ready :white_check_mark:

#589 fix: nav position on profile tab 👤📱
  apps/member-profile/app/routes/_profile.profile.tsx
Labels: Ready :white_check_mark:

#592 feat: notify members when securing the bag 💰
  packages/core/src/infrastructure/bull/bull.types.ts
  packages/core/src/modules/slack/slack.worker.ts
  packages/core/src/modules/slack/use-cases/add-slack-message.ts
  packages/core/src/modules/slack/use-cases/send-secured-the-bag-reminder.ts
Labels: Ready :white_check_mark:, Bloomberg

#597 feat: add resume review nudge ✍️
  packages/core/src/api.ts
  packages/core/src/infrastructure/bull/bull.types.ts
  packages/core/src/modules/resume-review/resume-review.ts
  packages/core/src/modules/slack/use-cases/add-slack-message.ts
  packages/db/src/shared/utils.ts
Labels: Ready :white_check_mark:, Bloomberg

#598 feat: implement ai chatbot reaction response 🤖
  apps/api/src/routers/slack.router.ts
  packages/core/src/infrastructure/bull/bull.types.ts
  packages/core/src/modules/slack/events/slack-reaction-added.ts
  packages/core/src/modules/slack/slack.ts
  packages/core/src/modules/slack/slack.worker.ts
Labels: Ready :white_check_mark:, Bloomberg

#605 feat: notify admins when a thread has 100 messages 🚨
  apps/api/src/routers/slack.router.ts
  apps/api/src/routers/slack.types.ts
  packages/core/src/infrastructure/bull/bull.types.ts
  packages/core/src/modules/slack/use-cases/add-slack-message.ts
Labels: Ready :white_check_mark:, Bloomberg

#612 feat: add confirmation that user has searched for duplicate resources ✅
  apps/member-profile/app/routes/_profile.resources.add.tsx
  apps/member-profile/app/shared/components/resource-form.tsx
Labels: Ready :white_check_mark:

#615 feat: implement delete resource functionality 🕳️👨‍🦯
  apps/member-profile/app/routes/_profile.resources.$id_.delete.tsx
  apps/member-profile/app/routes/_profile.resources.$id_.edit.tsx
  apps/member-profile/app/shared/constants.ts
  packages/core/src/modules/resources/index.server.ts
  packages/core/src/modules/resources/use-cases/delete-resource.ts
  packages/db/src/migrations/20241210235120_resource_cascade_delete.ts
Labels: Ready :white_check_mark:
